version: '3.9'
services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: prisma
      MYSQL_USER: prisma
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    secrets:
      - db_password
secrets:
  db_password:
    file: db_password.txt
volumes:
    db_data:


